[project]
name = "agentic-apigee-infra"
version = "0.1.0"
description = "This project generates all the infrastructure resources required for Agentic Apigee"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
]
